version: '3.9'
services:
  app:
    environment:
      APPLICATION_ENV: development
    ports:
      - 8080:80
    expose:
      - 8080

  db:
    environment:
      MYSQL_DATABASE: app-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

  adminer:
    ports:
      - 8081:8080
    environment:
      ADMINER_DB: app-db
      ADMINER_DRIVER: server
      ADMINER_SERVER: db
      ADMINER_USERNAME: root
      ADMINER_PASSWORD: root
      ADMINER_AUTOLOGIN: 1